services:
  app:
    environment:
      AUTH_PROVIDERS: local,pocketid

      AUTH_POCKETID_DRIVER: openid
      AUTH_POCKETID_LABEL: Pocket ID
      AUTH_POCKETID_ICON: account_circle
      AUTH_POCKETID_SCOPE: openid profile email
      AUTH_POCKETID_IDENTIFIER_KEY: email
      AUTH_POCKETID_ALLOW_PUBLIC_REGISTRATION: "true"

      AUTH_POCKETID_CLIENT_ID: ${AUTH_POCKETID_CLIENT_ID}
      AUTH_POCKETID_CLIENT_SECRET: ${AUTH_POCKETID_CLIENT_SECRET}
      AUTH_POCKETID_ISSUER_URL: ${AUTH_POCKETID_ISSUER_URL}
      AUTH_POCKETID_DEFAULT_ROLE_ID: ${AUTH_POCKETID_DEFAULT_ROLE_ID}
      AUTH_POCKETID_REDIRECT_ALLOW_LIST: ${AUTH_POCKETID_REDIRECT_ALLOW_LIST}